u = SuperAdmin(userName='Olivier11', userFirstName='Baraka', userLastName='Mushagi', userEmail='oliver@gmai.com', user_phone_number='+243970353087', userGender='male', userDateOfBirth='14/11/1993')



  Python 3.9.12 (main, Apr 18 2022, 22:40:46) 
[GCC 9.4.0] on linux
App: sgp [production]
Instance: /home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/instance
>>> u = SuperAdmin(userName='Olivier11', userFirstName='Baraka', userLastName='Mushagi', userEmail='oliver@gmai.com', user_phone_number='+243970353087', userGender='male', userDateOfBirth='(14-11-1993)')
>>> u.set_password('cat')
>>> db.session.add(u)
>>> db.session.commit()
Traceback (most recent call last):
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1719, in _execute_context
    context = constructor(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1070, in _init_compiled
    param = [
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1071, in <listcomp>
    processors[key](compiled_params[key])
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1068, in process
    raise TypeError(
TypeError: SQLite Date type only accepts Python date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line 2, in commit
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1435, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3367, in flush
    self._flush(objects)
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3507, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3467, in _flush
    flush_context.execute()
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1725, in _execute_context
    self._handle_dbapi_exception(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1719, in _execute_context
    context = constructor(
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1070, in _init_compiled
    param = [
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1071, in <listcomp>
    processors[key](compiled_params[key])
  File "/home/albin/Desktop/project&doc_2022/2022Projects/SGP_FSTA_Webapp/env/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1068, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite Date type only accepts Python date objects as input.
[SQL: INSERT INTO user ("userName", "userFirstName", "userLastName", "userEmail", user_phone_number, "userProfilePic", "userPassword", "userStatus", "userGender", "userDateOfBirth", "userLoginAt", "userCreationDate", type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'userName': 'Olivier11', 'userLastName': 'Mushagi', 'user_phone_number': '+243970353087', 'userPassword': 'pbkdf2:sha256:260000$72hZrIbaOR2A098V$861 ... (52 characters truncated) ... 99afe95c7', 'userEmail': 'oliver@gmai.com', 'userGender': 'male', 'type': 'superadmin', 'userDateOfBirth': '(14-11-1993)', 'userFirstName': 'Baraka'}]]
>>> 

 # userDateOfBirth = db.Column(db.Date())

u = SuperAdmin(userName='Olivier11', userFirstName='Baraka', userLastName='Mushagi', userEmail='oliver@gmai.com', user_phone_number='+243970353087', userGender='male', userDateOfBirth='(14-11-1993)')

u.set_password('cat')

db.session.add(u)

db.session.commit()
